name: Build Android app

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install nodejs

      - name: Setup JAVA 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Clone TizenTube to assets
        working-directory: androidApp/app/src/main/assets
        run: git clone https://github.com/reisxd/TizenTube.git tizentube
      
      - name: Install TizenTube modules
        working-directory: androidApp/app/src/main/assets/tizentube
        run: |
          npm i
          rm -rf .git
          rm -rf apps
        
      - name: Install TizenTube Mods modules and Build it
        working-directory: androidApp/app/src/main/assets/tizentube/mods
        run: |
          npm i
          npm run build
          rm -r node_modules
        
      - name: Build Release apk
        working-directory: androidApp/
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: androidApp/app/build/outputs/apk/debug/
   
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ env.RELEASE_VERSION }}
          files: androidApp/app/build/outputs/apk/debug/app-debug.apk