name: Build Android app

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y upgrade
          sudo apt -y install nodejs

      - name: Setup JAVA 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Change directory
        run: cd androidApp

      - name: Install modules
        run: |
          cd app/src/main/assets
          git clone https://github.com/reisxd/TizenTube.git tizentube
          cd tizentube
          npm i
          cd mods
          npm i
          npm run build
          rm -r node_modules
          cd ../../../../..
      - name: Build Release apk
        run: ./gradlew build

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          paths: |
            app/build/outputs/apk/debug/
   
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ env.RELEASE_VERSION }}
          files: |
            app/build/outputs/apk/debug/app-debug.apk